{{- if and .Values.authProxyClusterRole.enabled .Values.authProxy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.authProxyClusterRoleName" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.authProxyClusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ include "chart.authProxyClusterRoleName" . }}-reader"
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.authProxyClusterRole.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
{{- end }}