apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: http-metrics
      targetPort: http-metrics
      protocol: TCP
  selector:
    control-plane: controller-manager-mimirrules
    {{- include "chart.selectorLabels" . | nindent 4 }}
