title: Mimir Rules K8S Controller
description: K8S controller to manage Grafana Mimir Alerting and Recording rules.
show_downloads: false
google_analytics:
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme