title: Mimir Rules K8S Controller
description: K8S controller to manage Mimir Alerting and Recording rules with dynamic tenants, based on namespace name or annotations.
show_downloads: true
google_analytics:
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme