# permissions for end users to edit mimirrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: mimirrules-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: o11y-rules-telemetry-operator
    app.kubernetes.io/part-of: o11y-rules-telemetry-operator
    app.kubernetes.io/managed-by: kustomize
  name: mimirrules-editor-role
rules:
- apiGroups:
  - mimirrules.telemetry.springernature.com
  resources:
  - mimirrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mimirrules.telemetry.springernature.com
  resources:
  - mimirrules/status
  verbs:
  - get
